name: Build and release JAR files

on:
  release:
    types:
      - published

jobs:
  upload-jar:
    runs-on: ubuntu-latest
    permissions:
      contents: write # release changes require contents write

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - uses: actions/setup-java@v3
      with:
        java-version: "8"
        distribution: temurin

    - name: Generate JARs
      run: mvn clean package -DskipTests

    - name: Set project version env variable
      run: |
        echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Build and upload JAR
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} target/spark-${{ env.PROJECT_VERSION }}.jar